included:
  - Passepartout/App
  - Passepartout/Library/Sources
  - Passepartout/Library/Tests
  - Passepartout/Shared
  - Passepartout/Tunnel
analyzer_rules:
  - unused_declaration
  - unused_import
opt_in_rules:
  - sorted_imports
disabled_rules:
  - cyclomatic_complexity
  - file_length
  - force_cast
  - function_body_length
  - identifier_name
  - line_length
  - inclusive_language
  - nesting
  - todo
  - type_name
