# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

automatic_release false
skip_binary_upload true
skip_metadata false
skip_screenshots false
#overwrite_screenshots true
run_precheck_before_submit false
