# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/

screenshots_path "#{ENV["APP_ROOT"]}/fastlane/screenshots"
metadata_path "#{ENV["APP_ROOT"]}/fastlane/metadata"

if ENV["PLATFORM"] == "ios"
    ipa "dist/ios/Passepartout.ipa"
else
    pkg "dist/mac/Passepartout.pkg"
end

skip_binary_upload true
skip_metadata false
skip_screenshots false
#overwrite_screenshots true
run_precheck_before_submit false
