#!/bin/bash
platforms="iOS macOS tvOS"
devices="mac iphone ipad appletv"
changelog="CHANGELOG.txt"
metadata_root="fastlane/metadata"
metadata_path="default/release_notes.txt"
api_git="https://github.com/passepartoutvpn/api"
api_version="v5"
api_path=".api"
api_package_path="Packages/App/Sources/CommonAPI/API"
translations_input_path="l10n"
translations_output_path="Packages/App/Sources/UILibrary/Resources"
