#!/bin/bash
platforms="iOS macOS tvOS"
devices="iphone ipad mac appletv"
changelog="CHANGELOG.txt"
metadata_root="fastlane/metadata"
metadata_path="default/release_notes.txt"
api_git="https://github.com/passepartoutvpn/api"
api_version="v5"
api_path=".api"
api_package_path="Library/Sources/CommonAPI/API"
